version: "3.7"

services:
  web:
    container_name: web
    build: ./services/web
    volumes:
      - static_volume:/home/app/web/project/static
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=./services/web/project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgresql://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT/$DB_NAME

    depends_on:
      - db
  db:
    ports:
      - "5432:5432"
    build:
      context: ./services/web/project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
  nginx:
    build: ./services/nginx
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    ports:
      - 8080:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: